swagger: '2.0'
info: 
  version: 0.0.1
  title: GAAP API
host: 'localhost:5000'
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  BasicAuth:
    type: basic
security:
  - BasicAuth: []
parameters: 
  pageParam:
    name: page
    in: query
    description: The page number
    required: false
    type: integer
  pageSizeParam:
    name: pageSize
    in: query
    description: Max numer of elements per page
    required: false
    type: integer
paths:
  /swagger:
    x-swagger-pipe: swagger_raw 
  #---------Example Endpoints-------------------
  /example:
    x-swagger-router-controller: ExampleController
    x-typeorm-repository-name: ExampleUser
    post:
      x-security-privilege: 'test:write'
      operationId: createExampleUser
      description: Create a new example user
      tags:
        - example
      parameters:
        - name: exampleUser
          description: user
          in: body
          schema:
            $ref: '#/definitions/ExampleUser'
      responses:
        '200':
          description: Test successful
          schema:
            $ref: '#/definitions/ExampleResponse'
        '400':
          description: Test unsuccessful
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: Test unsuccessful
          schema:
            $ref: '#/definitions/ErrorResponse'
  /example/{id}:
    x-swagger-router-controller: ExampleController
    x-typeorm-repository-name: ExampleUser
    get:
      x-security-privilege: 'test:read'
      operationId: readExampleUser
      description: Find an example user by id
      tags:
        - example
      parameters:
        - name: id
          type: string
          format: uuid
          in: path
          required: true
      responses:
        '200':
          description: Test successful
          schema:
            $ref: '#/definitions/ExampleResponse'
        '404':
          description: Test unsuccessful
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: Test unsuccessful
          schema:
            $ref: '#/definitions/ErrorResponse'
    put:
      x-security-privilege: 'test:write'
      operationId: updateExampleUser
      description: Update an example user by id
      tags:
        - example
      parameters:
        - name: id
          type: string
          format: uuid
          in: path
          required: true
        - name: exampleUser
          description: user
          in: body
          schema:
            $ref: '#/definitions/ExampleUser'
      responses:
        '200':
          description: Test successful
          schema:
            $ref: '#/definitions/ExampleResponse'
        '404':
          description: Test unsuccessful
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: Test unsuccessful
          schema:
            $ref: '#/definitions/ErrorResponse'
    delete:
      x-security-privilege: 'test:delete'
      operationId: deleteExampleUser
      description: Delete an example user by id
      tags:
        - example
      parameters:
        - name: id
          type: string
          format: uuid
          in: path
          required: true
      responses:
        '200':
          description: Test successful
          schema:
            $ref: '#/definitions/ExampleResponse'
        '404':
          description: Test unsuccessful
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: Test unsuccessful
          schema:
            $ref: '#/definitions/ErrorResponse'
  #-------//Example Endpoints-------------------

definitions:
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  ExampleUser:
    type: object
    properties:
        firstName:
          type: string
        lastName:
          type: string
        age:
          type: number
  ExampleResponse:
    allOf:
      - type: object
        properties:
          id:
            type: string
            format: uuid
      - $ref: '#/definitions/ExampleUser'
