swagger:
  fittingsDirs: [api/fittings, node_modules]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers
  bagpipes:
    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [api/mocks]
      controllersDirs: [api]
    _swagger_validate:
      name: swagger_validator
      validateResponse: true
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_security
      - swagger_params_parser
      - _swagger_validate
      - express_compatibility
      - _router
    swagger_raw:
      name: swagger_raw
