name: PostgreSQL service example
on:
  pull_request:
    branches: [ master, develop ]

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:14.16.0
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
  server-job:
    runs-on: ubuntu-latest
    needs: container-job
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v2

      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html

      - name: Install dependencies
        run: npm ci
      - name: Build JS
        run: npm run build
      - name: Run Source ORM Tests
        run: npm run test-orm
        requires: 
        env:
          PG_HOST: localhost
          PG_PORT: 5432
          PG_USERNAME: postgres
          PG_PASSWORD: root
          PG_DATABASE: gaap
          PG_SCHEMA: public