name: PostgreSQL service example
on:
  pull_request:
    branches: [ master, develop ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:14.16.0
    services:
      postgres:
        image: postgres:10.16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gaap
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      # Downloads a copy of the code in your repository before running CI tests
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Setup .env
          run: cp .env.example .env
        - name: Install dependencies
          run: npm ci
        - name: Build JS
          run: npm run build
        - name: Run Source ORM Tests
          run: npm run test-orm
          env: 
            PG_PORT: ${{ job.services.postgres.ports[5432] }}