name: PostgreSQL service example
on:
  pull_request:
    branches: [ master, develop ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:14.16.0
    services:
      postgres:
        image: postgres:10.16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gaap
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      # Downloads a copy of the code in your repository before running CI tests
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Install dependencies
          run: npm ci
        - name: Build JS
          run: npm run build
        - name: Run Source ORM Tests
          run: npm run test-orm
          env: 
            PG_HOST: localhost
            PG_PORT: ${{ job.services.postgres.ports[5432] }}
            PG_USERNAME: postgres
            PG_PASSWORD: root
            PG_DATABASE: gaap
            PG_SCHEMA: public