name: Node Continuous Testing

on:
  pull_request:
    branches: [ master, develop ]


jobs:
  test_pr:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 14.16.0
      - name: Install dependencies
        run: npm ci
      - name: Build JS
        run: npm run build
      - name: Run Source Code Tests
        run: npm run test-src